### This file is automatically generated by Qt Design Studio.
### Do not change

add_subdirectory(HeliContent)
add_subdirectory(Generated)
add_subdirectory(Heli)
add_subdirectory(App)

target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE
    HeliContentplugin
    Generated_QtQuick3D_MD_902_Explorerplugin
    Heliplugin)